// Mustache.js
var Mustache="undefined"!==typeof module&&module.exports||{};
(function(j){function H(a){return String(a).replace(/&(?!\w+;)|[<>"']/g,function(a){return I[a]||a})}function u(a,c,d,e){for(var e=e||"<template>",b=c.split("\n"),f=Math.max(d-3,0),g=Math.min(b.length,d+3),b=b.slice(f,g),i=0,l=b.length;i<l;++i)g=i+f+1,b[i]=(g===d?" >> ":"    ")+b[i];a.template=c;a.line=d;a.file=e;a.message=[e+":"+d,b.join("\n"),"",a.message].join("\n");return a}function v(a,c,d){if("."===a)return c[c.length-1];for(var a=a.split("."),e=a.length-1,b=a[e],f,g,i=c.length,l,j;i;){j=c.slice(0);
g=c[--i];for(l=0;l<e;){g=g[a[l++]];if(null==g)break;j.push(g)}if(g&&b in g){f=g[b];break}}"function"===typeof f&&(f=f.call(j[j.length-1]));return null==f?d:f}function J(a,c,d,e){var b="",a=v(a,c);if(e){if(null==a||!1===a||r(a)&&0===a.length)b+=d()}else if(r(a))z(a,function(a){c.push(a);b+=d();c.pop()});else if("object"===typeof a)c.push(a),b+=d(),c.pop();else if("function"===typeof a)var f=c[c.length-1],b=b+(a.call(f,d(),function(a){return s(a,f)})||"");else a&&(b+=d());return b}function A(a,c){for(var c=
c||{},d=c.tags||j.tags,e=d[0],b=d[d.length-1],f=['var buffer = "";',"\nvar line = 1;","\ntry {",'\nbuffer += "'],g=[],i=!1,l=!1,s=function(){if(i&&!l&&!c.space)for(;g.length;)f.splice(g.pop(),1);else g=[];l=i=!1},n=[],w,q,r,x=function(a){d=p(a).split(/\s+/);q=d[0];r=d[d.length-1]},y=function(a){f.push('";',w,'\nvar partial = partials["'+p(a)+'"];',"\nif (partial) {","\n  buffer += render(partial,stack[stack.length - 1],partials);","\n}",'\nbuffer += "')},v=function(b,d){var e=p(b);if(""===e)throw u(Error("Section name may not be empty"),
a,t,c.file);n.push({name:e,inverted:d});f.push('";',w,'\nvar name = "'+e+'";',"\nvar callback = (function () {","\n  return function () {",'\n    var buffer = "";','\nbuffer += "')},z=function(a){v(a,!0)},A=function(b){var b=p(b),d=0!=n.length&&n[n.length-1].name;if(!d||b!=d)throw u(Error('Section named "'+b+'" was never opened'),a,t,c.file);b=n.pop();f.push('";',"\n    return buffer;","\n  };","\n})();");b.inverted?f.push("\nbuffer += renderSection(name,stack,callback,true);"):f.push("\nbuffer += renderSection(name,stack,callback);");
f.push('\nbuffer += "')},B=function(a){f.push('";',w,'\nbuffer += lookup("'+p(a)+'",stack,"");','\nbuffer += "')},C=function(a){f.push('";',w,'\nbuffer += escapeHTML(lookup("'+p(a)+'",stack,""));','\nbuffer += "')},t=1,m,k,h=0,D=a.length;h<D;++h)if(a.slice(h,h+e.length)===e){h+=e.length;m=a.substr(h,1);w="\nline = "+t+";";q=e;r=b;i=!0;switch(m){case "!":h++;k=null;break;case "=":h++;b="="+b;k=x;break;case ">":h++;k=y;break;case "#":h++;k=v;break;case "^":h++;k=z;break;case "/":h++;k=A;break;case "{":b=
"}"+b;case "&":h++;l=!0;k=B;break;default:l=!0,k=C}m=a.indexOf(b,h);if(-1===m)throw u(Error('Tag "'+e+'" was not closed properly'),a,t,c.file);e=a.substring(h,m);k&&k(e);for(k=0;~(k=e.indexOf("\n",k));)t++,k++;h=m+b.length-1;e=q;b=r}else switch(m=a.substr(h,1),m){case '"':case "\\":l=!0;f.push("\\"+m);break;case "\r":break;case "\n":g.push(f.length);f.push("\\n");s();t++;break;default:E.test(m)?g.push(f.length):l=!0,f.push(m)}if(0!=n.length)throw u(Error('Section "'+n[n.length-1].name+'" was not closed properly'),
a,t,c.file);s();f.push('";',"\nreturn buffer;","\n} catch (e) { throw {error: e, line: line}; }");b=f.join("").replace(/buffer \+= "";\n/g,"");c.debug&&("undefined"!=typeof console&&console.log?console.log(b):"function"===typeof print&&print(b));return b}function B(a,c){var d=A(a,c),e=new Function("view,partials,stack,lookup,escapeHTML,renderSection,render",d);return function(b,d){var d=d||{},g=[b];try{return e(b,d,g,v,H,J,s)}catch(i){throw u(i.error,a,i.line,c.file);}}}function C(a,c){c=c||{};return!1!==
c.cache?(q[a]||(q[a]=B(a,c)),q[a]):B(a,c)}function s(a,c,d){return C(a)(c,d)}j.name="mustache.js";j.version="0.5.0-dev";j.tags=["{{","}}"];j.parse=A;j.compile=C;j.render=s;j.clearCache=function(){q={}};j.to_html=function(a,c,d,e){a=s(a,c,d);if("function"===typeof e)e(a);else return a};var K=Object.prototype.toString,D=Array.isArray,F=Array.prototype.forEach,G=String.prototype.trim,r;r=D?D:function(a){return"[object Array]"===K.call(a)};var z;z=F?function(a,c,d){return F.call(a,c,d)}:function(a,c,
d){for(var e=0,b=a.length;e<b;++e)c.call(d,a[e],e,a)};var E=/^\s*$/,p;if(G)p=function(a){return null==a?"":G.call(a)};else{var x,y;E.test("\u00a0")?(x=/^\s+/,y=/\s+$/):(x=/^[\s\xA0]+/,y=/[\s\xA0]+$/);p=function(a){return null==a?"":String(a).replace(x,"").replace(y,"")}}var I={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"},q={}})(Mustache);
// Tappable
(function(h,k){"function"===typeof define&&define.amd?define("tappable",[],function(){k(h,window.document);return h.tappable}):k(h,window.document)})(this,function(h,k){var d=function(){},z={noScroll:!1,activeClass:"tappable-active",onTap:d,onStart:d,onMove:d,onMoveOut:d,onMoveIn:d,onEnd:d,onCancel:d,allowClick:!1,boundMargin:50,noScrollDelay:0,activeClassDelay:0,inactiveClassDelay:0},E=(d="ontouchend"in document)?"touchstart":"mousedown",F=d?"touchmove":"mousemove",G=d?"touchend":"mouseup",A=function(b,
a){var c=k.elementFromPoint(b,a);3==c.nodeType&&(c=c.parentNode);return c},n=function(b){return b.replace(/\s+/g," ").replace(/^\s+|\s+$/g,"")},t=function(b,a){a&&(b.classList?b.classList.add(a):-1<n(b.className).indexOf(a)||(b.className=n(b.className+" "+a)))},p=function(b,a){a&&(b.classList?b.classList.remove(a):b.className=b.className.replace(RegExp("(^|\\s)"+a+"(?:\\s|$)"),"$1"))},B=function(b,a){var c=!1;do c=k.documentElement,c=(c.matchesSelector||c.mozMatchesSelector||c.webkitMatchesSelector||
c.msMatchesSelector).call(b,a);while(!c&&(b=b.parentNode)&&b.ownerDocument);return c?b:!1};h.tappable=function(b,a){"function"==typeof a&&(a={onTap:a});var c={},d;for(d in z)c[d]=a[d]||z[d];var g=c.containerElement||k.body,e,h,l,m,q,r=!1,u=!1,j=c.activeClass,x=c.activeClassDelay,v,y=c.inactiveClassDelay,n,s=c.noScroll,C=c.noScrollDelay,D,w=c.boundMargin;g.addEventListener(E,function(f){var i;i=f.target;i||(i=f.targetTouches[0],i=A(i.clientX,i.clientY));var a=B(i,b);if(a){x?(clearTimeout(v),v=setTimeout(function(){t(a,
j)},x)):t(a,j);y&&a==h&&clearTimeout(n);l=f.clientX;m=f.clientY;if(!l||!m)i=f.targetTouches[0],l=i.clientX,m=i.clientY;e=a;u=r=!1;q=s?a.getBoundingClientRect():null;C&&(clearTimeout(D),s=!1,D=setTimeout(function(){s=!0},C));c.onStart.call(g,f,a)}},!1);g.addEventListener(F,function(f){if(e){s?f.preventDefault():clearTimeout(v);var a=f.target,b=f.clientX,d=f.clientY;if(!a||!b||!d){var h=f.changedTouches[0];b||(b=h.clientX);d||(d=h.clientY);a||(a=A(b,d))}s?b>q.left-w&&b<q.right+w&&d>q.top-w&&d<q.bottom+
w?(u=!1,t(e,j),c.onMoveIn.call(g,f,a)):(u=!0,p(e,j),c.onMoveOut.call(g,f,a)):r||(r=!0,p(e,j),c.onCancel.call(a,f));c.onMove.call(g,f,a)}},!1);g.addEventListener(G,function(a){if(e){clearTimeout(v);if(y){x&&!r&&t(e,j);var b=e;n=setTimeout(function(){p(b,j)},y)}else p(e,j);c.onEnd.call(g,a,e);var d=3==a.which||2==a.button;if(!r&&!u&&!d){var k=e;setTimeout(function(){c.onTap.call(g,a,k)},1)}h=e;e=null;setTimeout(function(){l=m=null},400)}},!1);g.addEventListener("touchcancel",function(a){e&&(p(e,j),
e=l=m=null,c.onCancel.call(g,a))},!1);c.allowClick||g.addEventListener("click",function(a){B(a.target,b)?a.preventDefault():l&&(m&&25>Math.abs(a.clientX-l)&&25>Math.abs(a.clientY-m))&&(a.stopPropagation(),a.preventDefault())},!1)}});